<a href="https://colab.research.google.com/github/Tanishka5D0/tani5d0/blob/main/assignments/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
import numpy as np
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
import numpy as np
x=np.array([100,20,34])
print("Size of the array:",x.size)
print("Memory size of one array element in bytes:",x.itemsize)
print("Memory size of numpy array in bytes:",x.size*x.itemsize)

Size of the array: 3
Memory size of one array element in bytes: 8
Memory size of numpy array in bytes: 24


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
import numpy as np
x=np.zeros(10, dtype=int)
if x[5]==0:
    x[5]=1
print(x)

[0 0 0 0 0 1 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
import numpy as np
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
import numpy as np
y=np.arange(100)
y= y[::-1]
print(y)

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
s=np.nonzero([1,2,0,0,4,0])
print(s)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
N=np.eye(3)
print(N)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
Y=np.random.random((3,3,3))
print(Y)

[[[0.96912018 0.73046414 0.33420789]
  [0.80614701 0.51278606 0.26946398]
  [0.33396499 0.05390415 0.69680815]]

 [[0.15483459 0.45653696 0.67577795]
  [0.55072518 0.90453108 0.01927691]
  [0.10836697 0.94894382 0.56613241]]

 [[0.56425637 0.76363391 0.5947245 ]
  [0.95131434 0.55873517 0.69608357]
  [0.83448063 0.81099037 0.27370766]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
X=np.random.random((10,10))
Xmin,Xmax=X.min(),X.max()
print(Xmin,Xmax)

0.024001291638077404 0.9894611496134286


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
y=np.random.random(30)
m=y.mean()
print(m)

0.4818031039172606


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
a=np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
import numpy as np
A= np.ones((8,8))
A=np.pad(A, pad_width=1, mode='constant',constant_values=0)
print(A)
A[:,[0,-1]] = 0
A[[0,-1], :] = 0
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
print(0 * np.nan)
print(np.nan==np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
X=np.diag(1+np.arange(4),k=-1)
print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
M=np.zeros((8,8),dtype=int)
M[1::2,::2] =1
M[::2,1::2] =1
print(M)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [23]:
import numpy as np
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
import numpy as np
X= np.tile(np.array([[0,1], [1,0]]), (4,4))
print (X)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [25]:
T=np.random.random((5,5))
T=(T-np.mean(T))/(np.std(T))
print(T)

[[-1.57529625 -0.36632862  0.61467777 -1.25986414  0.43516595]
 [ 0.25478588  1.7332775  -0.49127521 -1.21098595  0.19857096]
 [ 0.99556712 -1.59018934  0.00409358 -1.08002736 -0.28302253]
 [ 0.1231953  -1.31519409  1.24010204 -0.61767133 -0.56758031]
 [ 0.53586505  1.75860925 -0.04924511  1.50255574  1.0102141 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [26]:
import numpy as np
color = np.dtype([("r",np.ubyte),
                  ("g",np.ubyte),
                  ("b",np.ubyte),
                  ("a",np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [27]:
A=np.dot(np.ones((5,3)), np.ones((3,2)))
print(A)
A=np.ones((5,3)) @ np.ones((3,2))
print(A)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
[0, 1, 2, 3, -4, -5, -6, -7, -8, 9, 10]

[0, 1, 2, 3, -4, -5, -6, -7, -8, 9, 10]

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [31]:
# Assuming you want Z to be an array of numbers,
# for example, an array of floats:
import numpy as np

Z = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
Z = Z.astype(int)
2 << Z >> 2

array([ 1,  2,  4,  8, 16])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [32]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-32-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-32-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-32-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [33]:
Z= np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 1. -5.  8.  2. -8. -8.  5.  6.  6.  1.]
[ 1. -5.  8.  2. -8. -8.  5.  6.  6.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [34]:
A1=np.random.randint(0,200,200)
A2=np.random.randint(0,200,200)
print(np.intersect1d(A1,A2))

[  1   2   3   4   5   8   9  10  11  12  15  16  20  21  22  24  27  29
  34  35  36  38  39  40  45  52  61  63  66  67  68  69  73  74  81  84
  86  87  90 100 103 104 106 107 110 113 115 119 124 125 128 132 133 134
 143 147 148 151 154 157 158 160 163 178 179 181 182 185 187 188 189 192
 193 195 198]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [35]:
defaults = np.seterr(all="ignore")
X=np.ones(1)/0
np.seterr(**defaults)
with np.errstate(all="ignore"):
    np.arange(3)/0
    X=np.arange(3)/0
    print(X)

[nan inf inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [36]:
import numpy as np
np.sqrt(-1)==np.emath.sqrt(-1)
np.sqrt(-1)==np.emath.sqrt(-1)

<ipython-input-36-5295bc09d449>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)
<ipython-input-36-5295bc09d449>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [37]:
import numpy as np
yesterday=np.datetime64('today')-np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today')+np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2024-12-01
2024-12-02
2024-12-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [39]:
L=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(L)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [40]:
X=np.ones(5)*2
Y=np.ones(5)*3
np.add(X,Y,out=Y)
np.divide(X,2,out=X)
np.negative(X,out=X)
np.multiply(X,Y,out=X)

array([-5., -5., -5., -5., -5.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [41]:
K=np.random.uniform(0,50,70)
print(K-K%1) # Removed extra indentation (two spaces)
print(np.floor(K))
print(np.ceil(K)-1)
print(K.astype(int))
print(np.trunc(K))

[ 0. 24. 31. 45. 10. 20. 33. 43.  5. 39. 42. 13. 27. 33. 30. 36. 18. 46.
 14. 47. 10. 32.  9. 23. 34. 27.  5. 26. 30. 26. 32.  9. 47. 27.  9. 36.
 21. 49. 14. 24. 29. 11.  0. 32. 16. 15. 49. 36. 37. 49. 25.  6. 12. 17.
  4. 14. 27. 19. 27. 29. 40.  6.  1. 24. 45. 32. 22. 18. 30. 27.]
[ 0. 24. 31. 45. 10. 20. 33. 43.  5. 39. 42. 13. 27. 33. 30. 36. 18. 46.
 14. 47. 10. 32.  9. 23. 34. 27.  5. 26. 30. 26. 32.  9. 47. 27.  9. 36.
 21. 49. 14. 24. 29. 11.  0. 32. 16. 15. 49. 36. 37. 49. 25.  6. 12. 17.
  4. 14. 27. 19. 27. 29. 40.  6.  1. 24. 45. 32. 22. 18. 30. 27.]
[ 0. 24. 31. 45. 10. 20. 33. 43.  5. 39. 42. 13. 27. 33. 30. 36. 18. 46.
 14. 47. 10. 32.  9. 23. 34. 27.  5. 26. 30. 26. 32.  9. 47. 27.  9. 36.
 21. 49. 14. 24. 29. 11.  0. 32. 16. 15. 49. 36. 37. 49. 25.  6. 12. 17.
  4. 14. 27. 19. 27. 29. 40.  6.  1. 24. 45. 32. 22. 18. 30. 27.]
[ 0 24 31 45 10 20 33 43  5 39 42 13 27 33 30 36 18 46 14 47 10 32  9 23
 34 27  5 26 30 26 32  9 47 27  9 36 21 49 14 24 29 11  0 32 16 15 49 36

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [42]:
Y=np.zeros((5,5))
Y+=np.arange(5)
print(Y)
Y=np.tile(np.arange(0,5),(5,1))
print(Y)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [43]:
def generate():
  for y in range(10):
    yield y
x=np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [44]:
Q=np.linspace(0,1,11,endpoint=False)[1:]
print(Q)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [45]:
N=np.random.random(10)
N.sort()
print(N)

[0.15309422 0.15658731 0.20080232 0.36472527 0.41127558 0.68304358
 0.72485863 0.83249362 0.86515469 0.86747257]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [46]:
B=np.arange(230)
np.add.reduce(B)

26335

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [47]:
A=np.random.randint(0,6,15)
B=np.random.randint(0,6,15)
equal=np.allclose(A,B)
print(equal)
equal=np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [48]:
Z = np.zeros(10)
Z[0] = 1
print(Z)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [49]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X*2+Y*2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.71092994 1.42082236 1.73086842 1.9231723  1.58097306 1.79767619
 1.38671121 1.51229033 1.33688892 1.27122642]
[0.69320608 0.95550157 0.85032395 0.77298745 0.93072218 1.01874286
 1.09460246 1.27862979 0.8539118  1.34043531]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [50]:
A=np.random.random(10)
A[A.argmax()]=0
print(A)

[0.64435399 0.23433207 0.95079096 0.18553546 0.82593784 0.91676904
 0.         0.59012312 0.1716289  0.88490587]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [51]:
Z = np.zeros((7,7), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,7),
                             np.linspace(0,1,7))
print(Z)

[[(0.        , 0.        ) (0.16666667, 0.        )
  (0.33333333, 0.        ) (0.5       , 0.        )
  (0.66666667, 0.        ) (0.83333333, 0.        )
  (1.        , 0.        )]
 [(0.        , 0.16666667) (0.16666667, 0.16666667)
  (0.33333333, 0.16666667) (0.5       , 0.16666667)
  (0.66666667, 0.16666667) (0.83333333, 0.16666667)
  (1.        , 0.16666667)]
 [(0.        , 0.33333333) (0.16666667, 0.33333333)
  (0.33333333, 0.33333333) (0.5       , 0.33333333)
  (0.66666667, 0.33333333) (0.83333333, 0.33333333)
  (1.        , 0.33333333)]
 [(0.        , 0.5       ) (0.16666667, 0.5       )
  (0.33333333, 0.5       ) (0.5       , 0.5       )
  (0.66666667, 0.5       ) (0.83333333, 0.5       )
  (1.        , 0.5       )]
 [(0.        , 0.66666667) (0.16666667, 0.66666667)
  (0.33333333, 0.66666667) (0.5       , 0.66666667)
  (0.66666667, 0.66666667) (0.83333333, 0.66666667)
  (1.        , 0.66666667)]
 [(0.        , 0.83333333) (0.16666667, 0.83333333)
  (0.33333333, 0.83333333) (

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [53]:
A=np.arange(16)
B=A+0.8
C=1.0/np.subtract.outer(A,B)
print(np.linalg.det(C))

17887483823.583435


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [54]:
import numpy as np
for dtype in[np.int8,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in[np.float32,float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [55]:
import numpy as np
np.set_printoptions(threshold=float("inf"))
P=np.zeros((60,30))
print(P)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [56]:
S=np.arange(350)
v=np.random.uniform(0,350)
index=(np.abs(S-v)).argmin()
print(S[index])

14


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [57]:
import numpy as np
Z = np.zeros(10, [('position', [('x', float, 1),
                                 ('y', float, 1)]),
                  ('color',    [('r', float, 1),
                                 ('g', float, 1),
                                 ('b', float, 1)])])

<ipython-input-57-1257cdfb8a9a>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [('position', [('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [58]:
import numpy as np
Z=np.random.random((10,2))
X,Y=np.atleast_2d(Z[:,0],Z[:,1])
D=np.sqrt((X-X.T)**2+(Y-Y.T)**2)
print(D)

[[0.         0.58297572 0.11415252 0.43119016 0.38150106 0.37710991
  0.4735012  0.43061648 0.73160857 0.43409756]
 [0.58297572 0.         0.51472531 0.24552635 0.64998651 0.62118346
  0.28509724 0.49899895 0.38713532 0.79757755]
 [0.11415252 0.51472531 0.         0.40820765 0.46384092 0.28238229
  0.4627347  0.47362862 0.62325155 0.37781609]
 [0.43119016 0.24552635 0.40820765 0.         0.40663946 0.61815564
  0.06842896 0.254987   0.59157849 0.76574715]
 [0.38150106 0.64998651 0.46384092 0.40663946 0.         0.74618369
  0.38932624 0.18389499 0.95109608 0.81506126]
 [0.37710991 0.62118346 0.28238229 0.61815564 0.74618369 0.
  0.68345697 0.74373937 0.53977682 0.18378274]
 [0.4735012  0.28509724 0.4627347  0.06842896 0.38932624 0.68345697
  0.         0.21962017 0.6490503  0.82707704]
 [0.43061648 0.49899895 0.47362862 0.254987   0.18389499 0.74373937
  0.21962017 0.         0.83836761 0.85011524]
 [0.73160857 0.38713532 0.62325155 0.59157849 0.95109608 0.53977682
  0.6490503  0.83836

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [59]:
z=(np.random.rand(10)*100).astype(np.float32)
y=z.view(np.int32)
y[:]=z
print(y)

[79 90 51 70 36  3 88 49 16 77]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [60]:
from io import StringIO
import numpy as np

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [61]:
A=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(A):
  print(index,value)
for index in np.ndindex(A.shape):
  print(index,A[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [62]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
z=np.sqrt(x*x+y*y)
sigma,mu=1.0,0.0
g=np.exp(-((z-mu)**2/(2.0*sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [63]:
n=20
p=5
z=np.zeros((n,n))
np.put(z,np.random.choice(range(n*n),p,replace=False),1)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [64]:
x=np.random.rand(5,10)
y=x-x.mean(axis=1,keepdims=True)
print(y)
y=x-x.mean(axis=1).reshape(-1,1)
print(y)

[[-0.02448529  0.18067421 -0.13469125  0.33766371  0.25740276 -0.02551106
  -0.50679285 -0.31188425 -0.18940526  0.41702929]
 [-0.4826597   0.36770631  0.36318119 -0.30216535  0.18925295  0.34196209
  -0.38831671 -0.14050517  0.06976497 -0.01822059]
 [ 0.38143759 -0.40868242 -0.29433813  0.07517772  0.39272243 -0.20993665
  -0.01231895  0.1558552   0.02224156 -0.10215836]
 [ 0.54043546  0.04097927 -0.1794706   0.05555082 -0.21115176 -0.10491805
  -0.20279464 -0.35701605  0.08507087  0.33331468]
 [ 0.14876753 -0.54378772  0.11979984  0.35411972  0.37872695  0.08387418
   0.27535278 -0.35641017 -0.06393991 -0.39650319]]
[[-0.02448529  0.18067421 -0.13469125  0.33766371  0.25740276 -0.02551106
  -0.50679285 -0.31188425 -0.18940526  0.41702929]
 [-0.4826597   0.36770631  0.36318119 -0.30216535  0.18925295  0.34196209
  -0.38831671 -0.14050517  0.06976497 -0.01822059]
 [ 0.38143759 -0.40868242 -0.29433813  0.07517772  0.39272243 -0.20993665
  -0.01231895  0.1558552   0.02224156 -0.10215836]

#### 59. How to sort an array by the nth column? (★★☆)

In [65]:
z=np.random.randint(0,20,(4,4))
print(z)
print(z[z[:,1].argsort()])

[[ 7 14 12 12]
 [18  2 16  3]
 [ 5  3 10  3]
 [16 12  2  2]]
[[18  2 16  3]
 [ 5  3 10  3]
 [16 12  2  2]
 [ 7 14 12 12]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [66]:
x=np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())
x=np.array([[0,1,np.nan],[1,2,np.nan],[4,5,np.nan]])
print(np.isnan(x))
print(np.isnan(x).all(axis=0))

False
[[False False  True]
 [False False  True]
 [False False  True]]
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [67]:
import numpy as np
Z=np.random.uniform(0,1,20)
z=0.5
m=Z.flat[np.abs(Z-z).argmin()]
print(m)

0.5210584784755921


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [68]:
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
it=np.nditer([A,B,None])
for x,y,z in it:z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [69]:
class NamedArray(np.ndarray):
  def __new__(cls,array,name="no name"):
    obj=np.asarray(array).view(cls)
    obj.name=name
    return obj
  def __array_finalize__(self,obj):
    if obj is None: return
    self.info=getattr(obj,'name',"no name")
Z=NamedArray(np.arange(10),'range_10')
print(Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [70]:
Z=np.ones(20)
I=np.random.randint(0,len(Z),30)
Z+=np.bincount(I,minlength=len(Z))
print(Z)
np.add.at(Z,I,1)
print(Z)

[2. 5. 1. 2. 3. 3. 3. 3. 3. 4. 2. 1. 6. 2. 1. 2. 1. 1. 2. 3.]
[ 3.  9.  1.  3.  5.  5.  5.  5.  5.  7.  3.  1. 11.  3.  1.  3.  1.  1.
  3.  5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [71]:
X=[6,5,4,3,2,1]
Y=[8,7,6,9,3,1]
Z=np.bincount(X,Y)
print(Z)

[0. 1. 3. 9. 6. 7. 8.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [72]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

I24 = np.dot(I.astype(np.uint32),[1,256,65536])

n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [73]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[48 56 62 53]
 [41 63 52 50]
 [45 47 63 50]]
[[48 56 62 53]
 [41 63 52 50]
 [45 47 63 50]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [74]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.44782109 0.63182559 0.49219851 0.48239061 0.38457521 0.44421833
 0.49885928 0.60547789 0.37341612 0.5448472 ]
0    0.447821
1    0.631826
2    0.492199
3    0.482391
4    0.384575
5    0.444218
6    0.498859
7    0.605478
8    0.373416
9    0.544847
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [75]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

np.sum(A * B.T, axis=1)

np.einsum("ij,ji->i", A, B)

array([0.8941765 , 0.45566872, 0.71483729, 1.35439245, 1.46097996])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [76]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [77]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [78]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [79]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 28) ( 0, 35) ( 1, 65) ( 1, 75) ( 3, 82) ( 3, 86) ( 5,  7) ( 5, 68)
 ( 7, 68) ( 9, 67) ( 9, 81) (18, 24) (18, 88) (24, 42) (24, 81) (24, 88)
 (28, 35) (42, 81) (61, 65) (61, 97) (63, 88) (63, 89) (65, 75) (65, 97)
 (66, 74) (67, 81) (74, 74) (82, 86) (88, 89)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [80]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [81]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))
from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [82]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)
Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [83]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.18330355,  0.93274073,  0.28528054,  0.23939673, -0.49982303,
        0.29038498, -0.04486582, -0.82863368, -0.57322094,  0.85516721,
       -0.48915184,  0.89815882,  0.00891973,  0.3518541 , -0.77263894,
        0.13226983, -0.33555824,  0.57438023,  0.4765699 , -0.89297476,
        0.57567512,  0.34845516,  0.26766061,  0.02680392,  0.46796162,
       -0.01889618,  0.19526702,  0.86178362, -0.41336003, -0.47378523,
        0.52390989, -0.09122064, -0.44115393,  0.92218018, -0.04578678,
        0.97371701,  0.71761118, -0.88493609, -0.75599472, -0.96254614,
        0.41991181, -0.04696222, -0.60767649,  0.43650958,  0.90401929,
        0.74902717, -0.51811592, -0.88846106, -0.35614781,  0.87979413,
       -0.59669759,  0.59804938, -0.17273513,  0.39472604,  0.97739728,
        0.34663252, -0.41397658, -0.73824857,  0.76782044, -0.27303926,
        0.47394602,  0.01929255,  0.18236512, -0.79239624,  0.91657763,
        0.84062888, -0.67121611,  0.30611506,  0.06450749, -0.03

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [84]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.19987401  0.86449897 11.86347246  1.35508978 14.50537178  0.18489543
  6.40746101 10.5339336   1.64293292  0.30882056]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [85]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[4.62228567e-01 1.30106862e+00 5.98433193e-01 7.44828063e+00
  2.36224819e-01 4.68580487e+00 6.05202781e+00 3.86197705e+00
  2.60797150e+00 1.23147792e-01]
 [1.05258493e+01 1.42611324e+01 1.45865668e+01 5.96027290e+00
  9.79550676e+00 3.62338769e-01 1.30188981e+00 9.24055014e+00
  6.98059358e+00 1.23154519e+01]
 [4.04652881e+00 5.18686414e+00 2.67601259e+00 6.30513309e+00
  1.08316890e+00 4.36823257e-02 8.25154039e+00 5.41029166e-02
  3.91421185e+00 2.38369239e-01]
 [2.30036168e+00 7.90194678e-01 2.49602508e+00 4.64767319e+00
  4.70256154e+00 8.60598062e+00 1.24547880e+00 4.23887691e+00
  1.85215032e+00 3.73916762e+00]
 [1.09660871e+00 7.18816850e+00 1.29355783e+01 6.77590080e+00
  1.64106643e+01 1.14837800e+01 9.73940314e+00 2.43086387e+00
  1.35674065e+01 1.56698253e+01]
 [3.51715679e+00 1.25846124e+00 5.81441133e+00 3.39243436e-01
  1.06109240e+01 1.26978287e+01 4.87412310e+00 3.60512644e+00
  7.75575812e+00 8.88518685e+00]
 [1.23236411e-01 4.69709473e+00 8.69175391e+00 2.08455876e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [87]:
import numpy as np
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

# Create a tuple of slice objects instead of a list
r = tuple(slice(start,stop) for start,stop in zip(R_start,R_stop))
z = tuple(slice(start,stop) for start,stop in zip(Z_start,Z_stop))

# Index the arrays using the tuple of slices
R[r] = Z[z]
print(Z)
print(R)

[[9 8 0 2 1 9 3 0 8 0]
 [7 2 3 3 5 4 7 8 6 6]
 [3 9 6 7 7 8 5 7 3 7]
 [9 7 2 0 6 3 0 9 6 3]
 [9 3 4 9 6 2 9 8 2 3]
 [8 4 6 3 5 0 4 5 2 4]
 [6 5 9 8 2 3 7 6 2 9]
 [1 1 6 0 4 1 5 3 7 9]
 [0 7 6 5 2 9 9 0 8 5]
 [7 5 0 4 6 5 1 2 6 4]]
[[0 0 0 0 0]
 [0 9 8 0 2]
 [0 7 2 3 3]
 [0 3 9 6 7]
 [0 9 7 2 0]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [88]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [89]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)
rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


#### 83. How to find the most frequent value in an array?

In [90]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [91]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[0 3 3]
   [2 2 2]
   [4 3 0]]

  [[3 3 2]
   [2 2 0]
   [3 0 0]]

  [[3 2 2]
   [2 0 3]
   [0 0 0]]

  [[2 2 3]
   [0 3 4]
   [0 0 0]]

  [[2 3 0]
   [3 4 1]
   [0 0 3]]

  [[3 0 2]
   [4 1 3]
   [0 3 1]]

  [[0 2 2]
   [1 3 3]
   [3 1 3]]

  [[2 2 2]
   [3 3 3]
   [1 3 4]]]


 [[[2 2 2]
   [4 3 0]
   [2 3 1]]

  [[2 2 0]
   [3 0 0]
   [3 1 3]]

  [[2 0 3]
   [0 0 0]
   [1 3 4]]

  [[0 3 4]
   [0 0 0]
   [3 4 3]]

  [[3 4 1]
   [0 0 3]
   [4 3 3]]

  [[4 1 3]
   [0 3 1]
   [3 3 1]]

  [[1 3 3]
   [3 1 3]
   [3 1 1]]

  [[3 3 3]
   [1 3 4]
   [1 1 0]]]


 [[[4 3 0]
   [2 3 1]
   [2 1 3]]

  [[3 0 0]
   [3 1 3]
   [1 3 0]]

  [[0 0 0]
   [1 3 4]
   [3 0 1]]

  [[0 0 0]
   [3 4 3]
   [0 1 0]]

  [[0 0 3]
   [4 3 3]
   [1 0 3]]

  [[0 3 1]
   [3 3 1]
   [0 3 3]]

  [[3 1 3]
   [3 1 1]
   [3 3 0]]

  [[1 3 4]
   [1 1 0]
   [3 0 3]]]


 [[[2 3 1]
   [2 1 3]
   [4 3 2]]

  [[3 1 3]
   [1 3 0]
   [3 2 0]]

  [[1 3 4]
   [3 0 1]
   [2 0 4]]

  [[3 4 3]
   [0 1 0]
   [0 4 4]]

  [[4 3 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [92]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  7 12 11  7]
 [ 7  0 13  6 10]
 [12 13  8 42  3]
 [11  6 42  2  9]
 [ 7 10  3  9  4]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [93]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [94]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)
Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [95]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0 0 1 1 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [96]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9995 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [97]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [98]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [2]:
import numpy as np  # Import numpy and assign it to the alias 'np'

x = np.random.rand(int(5e7))  # Now you can use 'np' to call numpy functions
Z = np.zeros(len(x), [('a', x.dtype)])
np.power(x, 3, out=Z['a'])
print(Z['a'])

[0.4746403  0.30826204 0.53293161 ... 0.02023463 0.17182997 0.20628446]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [3]:
import numpy as np

A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[...,np.newaxis,np.newaxis]==B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [4]:
import numpy as np
A = np.random.randint(0,5,(10,3))
print(A)
U=A[np.all(A[:,1:]==A[:,:-1],axis=1)]
print(U)
U=A[A.max(axis=1)!=A.min(axis=1),:]
print(U)

[[3 0 1]
 [3 4 3]
 [0 1 1]
 [1 3 0]
 [1 4 4]
 [4 2 2]
 [4 2 1]
 [1 0 4]
 [2 3 3]
 [0 4 0]]
[]
[[3 0 1]
 [3 4 3]
 [0 1 1]
 [1 3 0]
 [1 4 4]
 [4 2 2]
 [4 2 1]
 [1 0 4]
 [2 3 3]
 [0 4 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [5]:
I=np.array([0,1,2,3,15,16,32,64,128],dtype=np.uint8)
print(np.unpackbits(I[:,np.newaxis],axis=1))
I=np.array([0, 1, 2, 3, 15, 16, 32, 64, 128],dtype=np.uint8)
print(np.unpackbits(I[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [6]:
A=np.random.randint(0,4,(12,6))
T=np.ascontiguousarray(A).view(np.dtype((np.void,A.dtype.itemsize*A.shape[1])))
_,idx=np.unique(T,return_index=True)
uZ=A[idx]
print(uZ)

[[0 0 1 0 3 0]
 [0 0 3 1 1 0]
 [0 2 2 3 2 1]
 [1 0 3 3 0 1]
 [1 2 1 0 2 0]
 [1 2 3 3 1 0]
 [2 0 3 0 1 3]
 [2 0 3 2 0 1]
 [2 1 2 0 0 1]
 [2 3 0 0 3 2]
 [3 1 3 1 0 0]
 [3 1 3 1 2 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [7]:
X=np.random.uniform(0,2,20)
Y=np.random.uniform(0,2,20)
np.einsum('i->',X)
np.einsum('i,i->i',X,Y)
np.einsum('i,i',X,Y)
np.einsum('i,j->ij',X,Y)

array([[5.55644284e-01, 7.27259973e-01, 2.09505142e-01, 2.31235169e-01,
        2.13899711e-01, 8.67905266e-02, 2.47212524e-01, 3.35578558e-01,
        4.84757366e-01, 5.77304329e-01, 5.37589141e-01, 7.02047188e-01,
        7.19950377e-01, 4.54051704e-01, 3.99289242e-01, 4.69028778e-01,
        6.70811083e-01, 4.77451154e-01, 6.66636631e-01, 7.21790967e-01],
       [1.84343531e+00, 2.41279673e+00, 6.95065508e-01, 7.67158210e-01,
        7.09645164e-01, 2.87940911e-01, 8.20165542e-01, 1.11333344e+00,
        1.60825706e+00, 1.91529584e+00, 1.78353460e+00, 2.32914944e+00,
        2.38854602e+00, 1.50638631e+00, 1.32470343e+00, 1.55607506e+00,
        2.22551887e+00, 1.58401758e+00, 2.21166948e+00, 2.39465247e+00],
       [1.67206363e-01, 2.18849539e-01, 6.30449982e-02, 6.95840715e-02,
        6.43674267e-02, 2.61172997e-02, 7.43920314e-02, 1.00983438e-01,
        1.45874831e-01, 1.73724377e-01, 1.61773148e-01, 2.11262422e-01,
        2.16649910e-01, 1.36634779e-01, 1.20155473e-01, 1.4114

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [8]:
phi=np.arange(0,10*np.pi,0.1)
a=1
x=a*phi*np.cos(phi)
y=a*phi*np.sin(phi)
dr=(np.diff(x)**2+np.diff(y)**2)**.5
r=np.zeros_like(x)
r[1:]=np.cumsum(dr)
r_int=np.linspace(0,r.max(),200)
x_int=np.interp(r_int,r,x)
y_int=np.interp(r_int,r,y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [10]:
X=np.asarray([[1.0, 0.0, 3.0, 8.0],
[2.0, 0.0, 1.0, 1.0],
[1.5,2.5,1.0,0.0]])
n=4
M=np.logical_and.reduce(np.mod(X,1)==0,axis=-1)
M&=(X.sum(axis=-1)==n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [11]:
import numpy as np
import scipy.stats as st
np.random.seed(10)
X=np.random.randn(100)
N=1000
idx=np.random.randint(0,X.size,(N,X.size))
means=X[idx].mean(axis=1)
confint=np.percentile(means,[2.5,97.5])
print(confint)

[-0.11779332  0.25754188]
